Added files and added comments
kodeflap/Algo_Guide pull request #29
Opened 2022-10-08 13:22 UTC by CS50X-RGB

Fixes  issue  number #9

2022-10-08 13:23 UTC, CS50X-RGB commented
@kodeflap plz review my pr

2022-10-08 14:50 UTC, kodeflap commented
I will review your PR

2022-10-08 17:48 UTC, kodeflap requested changes
Thanks for the improved code. The suggestion is that there is no need for additional readme files for each sort in here. So you can remove it and can make other PR.

2022-10-08 17:48 UTC, kodeflap commented on app/src/main/java/com/dlight/algoguide/dsa/searching/linear_search/README.md
> +# WHAT IS LINEAR SEARCH
There is no need for this readme file

2022-10-08 17:48 UTC, kodeflap commented on app/src/main/java/com/dlight/algoguide/dsa/sorting/bubble_sort/README.md
> +## WHAT IS BUBBLE SORT
This readme is not required

2022-10-08 17:48 UTC, kodeflap commented on app/src/main/java/com/dlight/algoguide/dsa/sorting/insertion_sort/README.md
> +# WHAT IS INSERTATION SORT??
Readme file not required here

2022-10-08 20:51 UTC, CS50X-RGB commented
Ok I will fix it

2022-10-08 20:52 UTC, CS50X-RGB commented
Hi @kodeflap how can I make this this under the same pr??

2022-10-09 04:36 UTC, CS50X-RGB commented
@kodeflap i did the changes

2022-10-09 05:31 UTC, kodeflap approved these changes
your PR request will be merged

2022-10-09 05:33 UTC, merged