Hashing Code Added
kodeflap/Algo_Guide pull request #36
Opened 2022-10-09 17:19 UTC by aritra-tech

Added the code for Hashing Algorithm

2022-10-09 17:59 UTC, kodeflap commented
I will review it😃

2022-10-09 18:16 UTC, kodeflap requested changes
This PR request needs a class name change to avoid merge conflicts

2022-10-09 18:16 UTC, kodeflap commented on app/src/main/java/com/dlight/algoguide/dsa/hashing/Hashing.kt
> +class HashMap<K, V>() {
Rename the class name to Hashing

2022-10-09 18:54 UTC, aritra-tech commented on app/src/main/java/com/dlight/algoguide/dsa/hashing/Hashing.kt
> +class HashMap<K, V>() {
Ok I will do the changes

2022-10-09 20:00 UTC, aritra-tech commented
I have done the changes @kodeflap

2022-10-10 07:27 UTC, kodeflap approved these changes
Thank you for the modification this PR is approved

2022-10-10 07:28 UTC, merged